//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.eLearning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.eLearning.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the audio file.
        /// </summary>
        public static string AudioUpload {
            get {
                return ResourceManager.GetString("AudioUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a checkbox.
        /// </summary>
        public static string CompleteACheckbox {
            get {
                return ResourceManager.GetString("CompleteACheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a question.
        /// </summary>
        public static string CompleteAQuestion {
            get {
                return ResourceManager.GetString("CompleteAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a period of time (in seconds).
        /// </summary>
        public static string CompleteATimer {
            get {
                return ResourceManager.GetString("CompleteATimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is this content completed?.
        /// </summary>
        public static string CompletionCriteria {
            get {
                return ResourceManager.GetString("CompletionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFrame Url.
        /// </summary>
        public static string IFrame {
            get {
                return ResourceManager.GetString("IFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string RichText {
            get {
                return ResourceManager.GetString("RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an audio.
        /// </summary>
        public static string SelectAudio {
            get {
                return ResourceManager.GetString("SelectAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Audio from your course files.
        /// </summary>
        public static string SelectAudioList {
            get {
                return ResourceManager.GetString("SelectAudioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a document.
        /// </summary>
        public static string SelectDocument {
            get {
                return ResourceManager.GetString("SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a document from your course files.
        /// </summary>
        public static string SelectDocumentList {
            get {
                return ResourceManager.GetString("SelectDocumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a flash file.
        /// </summary>
        public static string SelectFlash {
            get {
                return ResourceManager.GetString("SelectFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a pdf file.
        /// </summary>
        public static string SelectPdf {
            get {
                return ResourceManager.GetString("SelectPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a video.
        /// </summary>
        public static string SelectVideo {
            get {
                return ResourceManager.GetString("SelectVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show IFrame As.
        /// </summary>
        public static string ShowIFrameAs {
            get {
                return ResourceManager.GetString("ShowIFrameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a question.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Name.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use  a Presentation.
        /// </summary>
        public static string UsePresentation {
            get {
                return ResourceManager.GetString("UsePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Video.
        /// </summary>
        public static string UseVideo {
            get {
                return ResourceManager.GetString("UseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use YouTube.
        /// </summary>
        public static string UseYouTube {
            get {
                return ResourceManager.GetString("UseYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
