//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.eLearning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CourseGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourseGroup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.eLearning.CourseGroup", typeof(CourseGroup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add course event to this group.
        /// </summary>
        public static string AlertFailAddCourse {
            get {
                return ResourceManager.GetString("AlertFailAddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add user to this group.
        /// </summary>
        public static string AlertFailAddUser {
            get {
                return ResourceManager.GetString("AlertFailAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add create new Group.
        /// </summary>
        public static string AlertFailCreate {
            get {
                return ResourceManager.GetString("AlertFailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faile to create course list.
        /// </summary>
        public static string AlertFailCreateCourseList {
            get {
                return ResourceManager.GetString("AlertFailCreateCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete Group.
        /// </summary>
        public static string AlertFailDelete {
            get {
                return ResourceManager.GetString("AlertFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to generate new group code.
        /// </summary>
        public static string AlertFailGroupCode {
            get {
                return ResourceManager.GetString("AlertFailGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to join group.
        /// </summary>
        public static string AlertFailJoin {
            get {
                return ResourceManager.GetString("AlertFailJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to load group.
        /// </summary>
        public static string AlertFailLoadGroup {
            get {
                return ResourceManager.GetString("AlertFailLoadGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to remove course event from this group.
        /// </summary>
        public static string AlertFailRemoveCourse {
            get {
                return ResourceManager.GetString("AlertFailRemoveCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to remove user from this group.
        /// </summary>
        public static string AlertFailRemoveUser {
            get {
                return ResourceManager.GetString("AlertFailRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update Group.
        /// </summary>
        public static string AlertFailUpdate {
            get {
                return ResourceManager.GetString("AlertFailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group  successfully added.
        /// </summary>
        public static string AlertSuccessCreate {
            get {
                return ResourceManager.GetString("AlertSuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully deleted.
        /// </summary>
        public static string AlertSuccessDelete {
            get {
                return ResourceManager.GetString("AlertSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been added to the group.
        /// </summary>
        public static string AlertSuccessJoin {
            get {
                return ResourceManager.GetString("AlertSuccessJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully updated.
        /// </summary>
        public static string AlertSuccessUpdate {
            get {
                return ResourceManager.GetString("AlertSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course completed / Course enrolled.
        /// </summary>
        public static string CourseInfo {
            get {
                return ResourceManager.GetString("CourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Events.
        /// </summary>
        public static string CourseLabel {
            get {
                return ResourceManager.GetString("CourseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Member.
        /// </summary>
        public static string GroupMember {
            get {
                return ResourceManager.GetString("GroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Group.
        /// </summary>
        public static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner.
        /// </summary>
        public static string LearnerLabel {
            get {
                return ResourceManager.GetString("LearnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Group name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Group.
        /// </summary>
        public static string TitleDescriptionList {
            get {
                return ResourceManager.GetString("TitleDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name already registered in the system.
        /// </summary>
        public static string ValidExistName {
            get {
                return ResourceManager.GetString("ValidExistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Group name.
        /// </summary>
        public static string ValidRequiredName {
            get {
                return ResourceManager.GetString("ValidRequiredName", resourceCulture);
            }
        }
    }
}
