//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.eLearning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.eLearning.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a question.
        /// </summary>
        public static string AnswerQuestion {
            get {
                return ResourceManager.GetString("AnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 1.
        /// </summary>
        public static string ApprovalLevelApprover1 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 2.
        /// </summary>
        public static string ApprovalLevelApprover2 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 3.
        /// </summary>
        public static string ApprovalLevelApprover3 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation/Amendment.
        /// </summary>
        public static string ApprovalLevelNone {
            get {
                return ResourceManager.GetString("ApprovalLevelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier.
        /// </summary>
        public static string ApprovalLevelVerifier {
            get {
                return ResourceManager.GetString("ApprovalLevelVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ApprovalStatusApproved {
            get {
                return ResourceManager.GetString("ApprovalStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string ApprovalStatusNone {
            get {
                return ResourceManager.GetString("ApprovalStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string ApprovalStatusRejected {
            get {
                return ResourceManager.GetString("ApprovalStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted For Approval.
        /// </summary>
        public static string ApprovalStatusSubmitted {
            get {
                return ResourceManager.GetString("ApprovalStatusSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press complete button.
        /// </summary>
        public static string ClickButton {
            get {
                return ResourceManager.GetString("ClickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Tube Video.
        /// </summary>
        public static string ExternalVideo {
            get {
                return ResourceManager.GetString("ExternalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFrame.
        /// </summary>
        public static string IFrame {
            get {
                return ResourceManager.GetString("IFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop up window.
        /// </summary>
        public static string PopUp {
            get {
                return ResourceManager.GetString("PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string Powepoint {
            get {
                return ResourceManager.GetString("Powepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a presentation.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text.
        /// </summary>
        public static string RichText {
            get {
                return ResourceManager.GetString("RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio from course files.
        /// </summary>
        public static string SavedAudio {
            get {
                return ResourceManager.GetString("SavedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a document from your files.
        /// </summary>
        public static string SavedDocument {
            get {
                return ResourceManager.GetString("SavedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test/Quiz.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a period of time (in seconds).
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an audio file.
        /// </summary>
        public static string UploadAudio {
            get {
                return ResourceManager.GetString("UploadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a document.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a video.
        /// </summary>
        public static string UploadVideo {
            get {
                return ResourceManager.GetString("UploadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Slideshare.
        /// </summary>
        public static string UseSlideshare {
            get {
                return ResourceManager.GetString("UseSlideshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
