//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.eLearning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.eLearning.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 1.
        /// </summary>
        public static string ApprovalLevelApprover1 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 2.
        /// </summary>
        public static string ApprovalLevelApprover2 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 3.
        /// </summary>
        public static string ApprovalLevelApprover3 {
            get {
                return ResourceManager.GetString("ApprovalLevelApprover3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation/Amendment.
        /// </summary>
        public static string ApprovalLevelNone {
            get {
                return ResourceManager.GetString("ApprovalLevelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier.
        /// </summary>
        public static string ApprovalLevelVerifier {
            get {
                return ResourceManager.GetString("ApprovalLevelVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ApprovalStatusApproved {
            get {
                return ResourceManager.GetString("ApprovalStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string ApprovalStatusNone {
            get {
                return ResourceManager.GetString("ApprovalStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string ApprovalStatusRejected {
            get {
                return ResourceManager.GetString("ApprovalStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted For Approval.
        /// </summary>
        public static string ApprovalStatusSubmitted {
            get {
                return ResourceManager.GetString("ApprovalStatusSubmitted", resourceCulture);
            }
        }
    }
}
