//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.AccountSetting", typeof(AccountSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Inactive Duration.
        /// </summary>
        public static string FieldInactiveDuration {
            get {
                return ResourceManager.GetString("FieldInactiveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contain lower case.
        /// </summary>
        public static string FieldIsContainLowerCase {
            get {
                return ResourceManager.GetString("FieldIsContainLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contain numeric.
        /// </summary>
        public static string FieldIsContainNumeric {
            get {
                return ResourceManager.GetString("FieldIsContainNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contain symbol.
        /// </summary>
        public static string FieldIsContainSymbol {
            get {
                return ResourceManager.GetString("FieldIsContainSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contain upper case.
        /// </summary>
        public static string FieldIsContainUpperCase {
            get {
                return ResourceManager.GetString("FieldIsContainUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length 8.
        /// </summary>
        public static string FieldIsLengthLimit {
            get {
                return ResourceManager.GetString("FieldIsLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Login Attempt Limit.
        /// </summary>
        public static string FieldIsLimitLoginAttempt {
            get {
                return ResourceManager.GetString("FieldIsLimitLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Password Expiry.
        /// </summary>
        public static string FieldIsPasswordExpiry {
            get {
                return ResourceManager.GetString("FieldIsPasswordExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Attempt Limit.
        /// </summary>
        public static string FieldLoginAttemptLimit {
            get {
                return ResourceManager.GetString("FieldLoginAttemptLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expiry Duration.
        /// </summary>
        public static string FieldPasswordExpiryDuration {
            get {
                return ResourceManager.GetString("FieldPasswordExpiryDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string FieldTerms {
            get {
                return ResourceManager.GetString("FieldTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Inactive Duration must be a number and greater than 0.
        /// </summary>
        public static string ValidNumericInactiveDuration {
            get {
                return ResourceManager.GetString("ValidNumericInactiveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Attempt Limit must be a number and greater than 0.
        /// </summary>
        public static string ValidNumericLoginAttemptLimit {
            get {
                return ResourceManager.GetString("ValidNumericLoginAttemptLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expiry Duration must be a number and greater than 0.
        /// </summary>
        public static string ValidNumericPasswordExpiryDuration {
            get {
                return ResourceManager.GetString("ValidNumericPasswordExpiryDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Terms of Use.
        /// </summary>
        public static string ValidRequiredTerms {
            get {
                return ResourceManager.GetString("ValidRequiredTerms", resourceCulture);
            }
        }
    }
}
