//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Carousel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carousel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Carousel", typeof(Carousel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Carousel.
        /// </summary>
        public static string BreadcrumbCreate {
            get {
                return ResourceManager.GetString("BreadcrumbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Carousel.
        /// </summary>
        public static string BreadcrumbDelete {
            get {
                return ResourceManager.GetString("BreadcrumbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Details.
        /// </summary>
        public static string BreadcrumbDetails {
            get {
                return ResourceManager.GetString("BreadcrumbDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Carousel.
        /// </summary>
        public static string BreadcrumbEdit {
            get {
                return ResourceManager.GetString("BreadcrumbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadcrumbHome {
            get {
                return ResourceManager.GetString("BreadcrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Carousel.
        /// </summary>
        public static string BreadcrumbManagement {
            get {
                return ResourceManager.GetString("BreadcrumbManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string BreadcrumbTitle {
            get {
                return ResourceManager.GetString("BreadcrumbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new carousel by filling in publication details below..
        /// </summary>
        public static string CreateDescription {
            get {
                return ResourceManager.GetString("CreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Carousel.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new carousel by filling in carousel details below..
        /// </summary>
        public static string HeadingDescriptionCreate {
            get {
                return ResourceManager.GetString("HeadingDescriptionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update carousel by filling in carousel details below..
        /// </summary>
        public static string HeadingDescriptionEdit {
            get {
                return ResourceManager.GetString("HeadingDescriptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit, delete and manage carousels..
        /// </summary>
        public static string HeadingDescriptionList {
            get {
                return ResourceManager.GetString("HeadingDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View carousel details below..
        /// </summary>
        public static string HeadingDescriptionView {
            get {
                return ResourceManager.GetString("HeadingDescriptionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Details.
        /// </summary>
        public static string HeadingDetails {
            get {
                return ResourceManager.GetString("HeadingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Carousel.
        /// </summary>
        public static string HeadingDetailsCreate {
            get {
                return ResourceManager.GetString("HeadingDetailsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Carousel.
        /// </summary>
        public static string HeadingDetailsEdit {
            get {
                return ResourceManager.GetString("HeadingDetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Carousel.
        /// </summary>
        public static string HeadingDetailsList {
            get {
                return ResourceManager.GetString("HeadingDetailsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Settings.
        /// </summary>
        public static string HeadingSettings {
            get {
                return ResourceManager.GetString("HeadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Sequence.
        /// </summary>
        public static string ManageSequence {
            get {
                return ResourceManager.GetString("ManageSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information marked with.
        /// </summary>
        public static string MandatoryPrefix {
            get {
                return ResourceManager.GetString("MandatoryPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is mandatory..
        /// </summary>
        public static string MandatorySuffix {
            get {
                return ResourceManager.GetString("MandatorySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill In Carousel Details.
        /// </summary>
        public static string SideBarStepCreate {
            get {
                return ResourceManager.GetString("SideBarStepCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Carousel Details.
        /// </summary>
        public static string SideBarStepEdit {
            get {
                return ResourceManager.GetString("SideBarStepEdit", resourceCulture);
            }
        }
    }
}
