//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DutyRoster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DutyRoster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.DutyRoster", typeof(DutyRoster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add new Duty Roster.
        /// </summary>
        public static string AlertFailCreate {
            get {
                return ResourceManager.GetString("AlertFailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete Duty Roster.
        /// </summary>
        public static string AlertFailDelete {
            get {
                return ResourceManager.GetString("AlertFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update Duty Roster.
        /// </summary>
        public static string AlertFailUpdate {
            get {
                return ResourceManager.GetString("AlertFailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster successfully added.
        /// </summary>
        public static string AlertSuccessCreate {
            get {
                return ResourceManager.GetString("AlertSuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster successfully deleted.
        /// </summary>
        public static string AlertSuccessDelete {
            get {
                return ResourceManager.GetString("AlertSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster successfully updated.
        /// </summary>
        public static string AlertSuccessUpdate {
            get {
                return ResourceManager.GetString("AlertSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DRDate {
            get {
                return ResourceManager.GetString("DRDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string DREndTime {
            get {
                return ResourceManager.GetString("DREndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer in-charge.
        /// </summary>
        public static string DROfficer {
            get {
                return ResourceManager.GetString("DROfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string DRStartTime {
            get {
                return ResourceManager.GetString("DRStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PlaceholderDate {
            get {
                return ResourceManager.GetString("PlaceholderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string PlaceholderEndTime {
            get {
                return ResourceManager.GetString("PlaceholderEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string PlaceholderStartTime {
            get {
                return ResourceManager.GetString("PlaceholderStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster.
        /// </summary>
        public static string SidebarDutyRoster {
            get {
                return ResourceManager.GetString("SidebarDutyRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster List.
        /// </summary>
        public static string SidebarDutyRosterList {
            get {
                return ResourceManager.GetString("SidebarDutyRosterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TitleDescriptionList {
            get {
                return ResourceManager.GetString("TitleDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Roster.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Date.
        /// </summary>
        public static string ValidRequiredDate {
            get {
                return ResourceManager.GetString("ValidRequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert End Time.
        /// </summary>
        public static string ValidRequiredEndTime {
            get {
                return ResourceManager.GetString("ValidRequiredEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Officer in-charge.
        /// </summary>
        public static string ValidRequiredOfficer {
            get {
                return ResourceManager.GetString("ValidRequiredOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Start Time.
        /// </summary>
        public static string ValidRequiredStartTime {
            get {
                return ResourceManager.GetString("ValidRequiredStartTime", resourceCulture);
            }
        }
    }
}
