//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Event {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Event() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Event", typeof(Event).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string AgendaDescription {
            get {
                return ResourceManager.GetString("AgendaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Reference No..
        /// </summary>
        public static string AgendaEventRefNo {
            get {
                return ResourceManager.GetString("AgendaEventRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person In-Charge.
        /// </summary>
        public static string AgendaPersonInCharge {
            get {
                return ResourceManager.GetString("AgendaPersonInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Document.
        /// </summary>
        public static string AgendaSupportDocument {
            get {
                return ResourceManager.GetString("AgendaSupportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        public static string AgendaTentative {
            get {
                return ResourceManager.GetString("AgendaTentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string AgendaTime {
            get {
                return ResourceManager.GetString("AgendaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda Session.
        /// </summary>
        public static string AgendaTitle {
            get {
                return ResourceManager.GetString("AgendaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Number.
        /// </summary>
        public static string AttBookingNumber {
            get {
                return ResourceManager.GetString("AttBookingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in Status.
        /// </summary>
        public static string AttCheckInStatus {
            get {
                return ResourceManager.GetString("AttCheckInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string AttCompanyName {
            get {
                return ResourceManager.GetString("AttCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Reference No.
        /// </summary>
        public static string AttEventId {
            get {
                return ResourceManager.GetString("AttEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyKad Number.
        /// </summary>
        public static string AttICNo {
            get {
                return ResourceManager.GetString("AttICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Name.
        /// </summary>
        public static string AttName {
            get {
                return ResourceManager.GetString("AttName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Type.
        /// </summary>
        public static string AttType {
            get {
                return ResourceManager.GetString("AttType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee Name.
        /// </summary>
        public static string AttUserId {
            get {
                return ResourceManager.GetString("AttUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AttUserType {
            get {
                return ResourceManager.GetString("AttUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string ExhibitorCompanyName {
            get {
                return ResourceManager.GetString("ExhibitorCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ExhibitorEmail {
            get {
                return ResourceManager.GetString("ExhibitorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibitor Name.
        /// </summary>
        public static string ExhibitorName {
            get {
                return ResourceManager.GetString("ExhibitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        public static string ExhibitorPhoneNo {
            get {
                return ResourceManager.GetString("ExhibitorPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string ExhibitorRemark {
            get {
                return ResourceManager.GetString("ExhibitorRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string ExRoadBranch {
            get {
                return ResourceManager.GetString("ExRoadBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string ExRoadEndDate {
            get {
                return ResourceManager.GetString("ExRoadEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string ExRoadEndTime {
            get {
                return ResourceManager.GetString("ExRoadEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string ExRoadEventName {
            get {
                return ResourceManager.GetString("ExRoadEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ExRoadExhibitionStatus {
            get {
                return ResourceManager.GetString("ExRoadExhibitionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ExRoadExhibitionStatusDesc {
            get {
                return ResourceManager.GetString("ExRoadExhibitionStatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Document.
        /// </summary>
        public static string ExRoadExhibitionSupDoc {
            get {
                return ResourceManager.GetString("ExRoadExhibitionSupDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ExRoadLocation {
            get {
                return ResourceManager.GetString("ExRoadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nominees.
        /// </summary>
        public static string ExRoadNomineeId {
            get {
                return ResourceManager.GetString("ExRoadNomineeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nominees.
        /// </summary>
        public static string ExRoadNomineeName {
            get {
                return ResourceManager.GetString("ExRoadNomineeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser Name.
        /// </summary>
        public static string ExRoadOrganiser {
            get {
                return ResourceManager.GetString("ExRoadOrganiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser Email.
        /// </summary>
        public static string ExRoadOrganiserEmail {
            get {
                return ResourceManager.GetString("ExRoadOrganiserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Requirement.
        /// </summary>
        public static string ExRoadParticipantRequirement {
            get {
                return ResourceManager.GetString("ExRoadParticipantRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive via.
        /// </summary>
        public static string ExRoadReceive_Via {
            get {
                return ResourceManager.GetString("ExRoadReceive_Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        public static string ExRoadReceivedById {
            get {
                return ResourceManager.GetString("ExRoadReceivedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        public static string ExRoadReceivedByName {
            get {
                return ResourceManager.GetString("ExRoadReceivedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        public static string ExRoadReceivedBys {
            get {
                return ResourceManager.GetString("ExRoadReceivedBys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string ExRoadReceivedDate {
            get {
                return ResourceManager.GetString("ExRoadReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string ExRoadRefNo {
            get {
                return ResourceManager.GetString("ExRoadRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ExRoadStartDate {
            get {
                return ResourceManager.GetString("ExRoadStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string ExRoadStartTime {
            get {
                return ResourceManager.GetString("ExRoadStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string MediaBranch {
            get {
                return ResourceManager.GetString("MediaBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string MediaRepDesignation {
            get {
                return ResourceManager.GetString("MediaRepDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string MediaRepEmail {
            get {
                return ResourceManager.GetString("MediaRepEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MediaRepMobileNumber {
            get {
                return ResourceManager.GetString("MediaRepMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep. Name.
        /// </summary>
        public static string MediaRepUserName {
            get {
                return ResourceManager.GetString("MediaRepUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PubEventAgencyFree {
            get {
                return ResourceManager.GetString("PubEventAgencyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PubEventCategoryId {
            get {
                return ResourceManager.GetString("PubEventCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PubEventCategoryName {
            get {
                return ResourceManager.GetString("PubEventCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string PubEventEndDate {
            get {
                return ResourceManager.GetString("PubEventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Exhibitors.
        /// </summary>
        public static string PubEventExternalExhibitorId {
            get {
                return ResourceManager.GetString("PubEventExternalExhibitorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Exhibitors.
        /// </summary>
        public static string PubEventExternalExhibitorName {
            get {
                return ResourceManager.GetString("PubEventExternalExhibitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string PubEventFee {
            get {
                return ResourceManager.GetString("PubEventFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PubEventIndividualFree {
            get {
                return ResourceManager.GetString("PubEventIndividualFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PubEventIndividualPaperFree {
            get {
                return ResourceManager.GetString("PubEventIndividualPaperFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PubEventIndividualPresentFree {
            get {
                return ResourceManager.GetString("PubEventIndividualPresentFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Rep..
        /// </summary>
        public static string PubEventLabelAgency {
            get {
                return ResourceManager.GetString("PubEventLabelAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Bird Fee (RM).
        /// </summary>
        public static string PubEventLabelEarlyBirdFee {
            get {
                return ResourceManager.GetString("PubEventLabelEarlyBirdFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free ?.
        /// </summary>
        public static string PubEventLabelFree {
            get {
                return ResourceManager.GetString("PubEventLabelFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string PubEventLabelIndividual {
            get {
                return ResourceManager.GetString("PubEventLabelIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual w/ Paper.
        /// </summary>
        public static string PubEventLabelIndividualPaper {
            get {
                return ResourceManager.GetString("PubEventLabelIndividualPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual w/ Paper To Present.
        /// </summary>
        public static string PubEventLabelIndividualPresent {
            get {
                return ResourceManager.GetString("PubEventLabelIndividualPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Fee (RM).
        /// </summary>
        public static string PubEventLabelNormalFee {
            get {
                return ResourceManager.GetString("PubEventLabelNormalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Type.
        /// </summary>
        public static string PubEventLabelParticipantType {
            get {
                return ResourceManager.GetString("PubEventLabelParticipantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Objective.
        /// </summary>
        public static string PubEventObjective {
            get {
                return ResourceManager.GetString("PubEventObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Allowed.
        /// </summary>
        public static string PubEventParticipantAllowed {
            get {
                return ResourceManager.GetString("PubEventParticipantAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string PubEventRefNo {
            get {
                return ResourceManager.GetString("PubEventRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PubEventRemarks {
            get {
                return ResourceManager.GetString("PubEventRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        public static string PubEventSpeakerId {
            get {
                return ResourceManager.GetString("PubEventSpeakerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        public static string PubEventSpeakerName {
            get {
                return ResourceManager.GetString("PubEventSpeakerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string PubEventStartDate {
            get {
                return ResourceManager.GetString("PubEventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PubEventStatus {
            get {
                return ResourceManager.GetString("PubEventStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PubEventStatusDesc {
            get {
                return ResourceManager.GetString("PubEventStatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Group.
        /// </summary>
        public static string PubEventTargetedGroup {
            get {
                return ResourceManager.GetString("PubEventTargetedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title .
        /// </summary>
        public static string PubEventTitle {
            get {
                return ResourceManager.GetString("PubEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string PubEventVenue {
            get {
                return ResourceManager.GetString("PubEventVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Category.
        /// </summary>
        public static string ReqEventCategory {
            get {
                return ResourceManager.GetString("ReqEventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Objective.
        /// </summary>
        public static string ReqEventObjective {
            get {
                return ResourceManager.GetString("ReqEventObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        public static string ReqEventRefNo {
            get {
                return ResourceManager.GetString("ReqEventRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title.
        /// </summary>
        public static string ReqEventTitle {
            get {
                return ResourceManager.GetString("ReqEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification/Cancellation Reasons.
        /// </summary>
        public static string ReqReason {
            get {
                return ResourceManager.GetString("ReqReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string ReqStatus {
            get {
                return ResourceManager.GetString("ReqStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string ReqType {
            get {
                return ResourceManager.GetString("ReqType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Document.
        /// </summary>
        public static string SpAttachment {
            get {
                return ResourceManager.GetString("SpAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Document.
        /// </summary>
        public static string SpAttachmentName {
            get {
                return ResourceManager.GetString("SpAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string SpEmail {
            get {
                return ResourceManager.GetString("SpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string SpExperience {
            get {
                return ResourceManager.GetString("SpExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        public static string SpPhoneNo {
            get {
                return ResourceManager.GetString("SpPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string SpPicture {
            get {
                return ResourceManager.GetString("SpPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string SpPictureName {
            get {
                return ResourceManager.GetString("SpPictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SpStatus {
            get {
                return ResourceManager.GetString("SpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SpStatusDesc {
            get {
                return ResourceManager.GetString("SpStatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Type.
        /// </summary>
        public static string SpType {
            get {
                return ResourceManager.GetString("SpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Type.
        /// </summary>
        public static string SpTypeDesc {
            get {
                return ResourceManager.GetString("SpTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Name.
        /// </summary>
        public static string SpUserId {
            get {
                return ResourceManager.GetString("SpUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Name.
        /// </summary>
        public static string SpUserName {
            get {
                return ResourceManager.GetString("SpUserName", resourceCulture);
            }
        }
    }
}
