//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Individual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Individual() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Individual", typeof(Individual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to activate user account.
        /// </summary>
        public static string AlertActivateFail {
            get {
                return ResourceManager.GetString("AlertActivateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account successfully activated.
        /// </summary>
        public static string AlertActivateSuccess {
            get {
                return ResourceManager.GetString("AlertActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to register user.
        /// </summary>
        public static string AlertCreateFail {
            get {
                return ResourceManager.GetString("AlertCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully registered. User will receive email with sign in details and link to activate the account..
        /// </summary>
        public static string AlertCreateSuccess {
            get {
                return ResourceManager.GetString("AlertCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to disable user account.
        /// </summary>
        public static string AlertDeactivateFail {
            get {
                return ResourceManager.GetString("AlertDeactivateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account successfully disable.
        /// </summary>
        public static string AlertDeactivateSuccess {
            get {
                return ResourceManager.GetString("AlertDeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete user account.
        /// </summary>
        public static string AlertDeleteFail {
            get {
                return ResourceManager.GetString("AlertDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account successfully delete.
        /// </summary>
        public static string AlertDeleteSuccess {
            get {
                return ResourceManager.GetString("AlertDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update user record.
        /// </summary>
        public static string AlertEditFail {
            get {
                return ResourceManager.GetString("AlertEditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User record successfully updated.
        /// </summary>
        public static string AlertEditSuccess {
            get {
                return ResourceManager.GetString("AlertEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to reset user account password.
        /// </summary>
        public static string AlertResetFail {
            get {
                return ResourceManager.GetString("AlertResetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account password successfully reset. User will receive email with link to reset account password.
        /// </summary>
        public static string AlertResetSuccess {
            get {
                return ResourceManager.GetString("AlertResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FieldAddress {
            get {
                return ResourceManager.GetString("FieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        public static string FieldCitizenship {
            get {
                return ResourceManager.GetString("FieldCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string FieldCountryId {
            get {
                return ResourceManager.GetString("FieldCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Number.
        /// </summary>
        public static string FieldICNo {
            get {
                return ResourceManager.GetString("FieldICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC / Passport Number.
        /// </summary>
        public static string FieldICPassportNo {
            get {
                return ResourceManager.GetString("FieldICPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        public static string FieldMalaysian {
            get {
                return ResourceManager.GetString("FieldMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string FieldMobileNo {
            get {
                return ResourceManager.GetString("FieldMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Malaysian.
        /// </summary>
        public static string FieldNonMalaysian {
            get {
                return ResourceManager.GetString("FieldNonMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string FieldPassportNo {
            get {
                return ResourceManager.GetString("FieldPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FieldPassword {
            get {
                return ResourceManager.GetString("FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string FieldPostCode {
            get {
                return ResourceManager.GetString("FieldPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string FieldRole {
            get {
                return ResourceManager.GetString("FieldRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string FieldStateId {
            get {
                return ResourceManager.GetString("FieldStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FieldStatus {
            get {
                return ResourceManager.GetString("FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 1.
        /// </summary>
        public static string PlaceholderAddress1 {
            get {
                return ResourceManager.GetString("PlaceholderAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 2.
        /// </summary>
        public static string PlaceholderAddress2 {
            get {
                return ResourceManager.GetString("PlaceholderAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Citizenship.
        /// </summary>
        public static string PlaceholderCitizenship {
            get {
                return ResourceManager.GetString("PlaceholderCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        public static string PlaceholderCity {
            get {
                return ResourceManager.GetString("PlaceholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string PlaceholderCountryId {
            get {
                return ResourceManager.GetString("PlaceholderCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IC Number.
        /// </summary>
        public static string PlaceholderICNo {
            get {
                return ResourceManager.GetString("PlaceholderICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        public static string PlaceholderMobileNo {
            get {
                return ResourceManager.GetString("PlaceholderMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Passport Number.
        /// </summary>
        public static string PlaceholderPassportNo {
            get {
                return ResourceManager.GetString("PlaceholderPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Postcode.
        /// </summary>
        public static string PlaceholderPostCode {
            get {
                return ResourceManager.GetString("PlaceholderPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string PlaceholderStateId {
            get {
                return ResourceManager.GetString("PlaceholderStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered in the system.
        /// </summary>
        public static string ValidIsExistEmail {
            get {
                return ResourceManager.GetString("ValidIsExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Number already registered in the system.
        /// </summary>
        public static string ValidIsExistICNo {
            get {
                return ResourceManager.GetString("ValidIsExistICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number already registered in the system.
        /// </summary>
        public static string ValidIsExistPassportNo {
            get {
                return ResourceManager.GetString("ValidIsExistPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered IC Number digit length must be 12.
        /// </summary>
        public static string ValidLengthICNo {
            get {
                return ResourceManager.GetString("ValidLengthICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered IC Number must be number.
        /// </summary>
        public static string ValidNumericICNo {
            get {
                return ResourceManager.GetString("ValidNumericICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Mobile Number must be number.
        /// </summary>
        public static string ValidNumericMobileNo {
            get {
                return ResourceManager.GetString("ValidNumericMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Postcode must be number.
        /// </summary>
        public static string ValidNumericPostCode {
            get {
                return ResourceManager.GetString("ValidNumericPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Address.
        /// </summary>
        public static string ValidRequiredAddress {
            get {
                return ResourceManager.GetString("ValidRequiredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Citizenship.
        /// </summary>
        public static string ValidRequiredCitizenshipId {
            get {
                return ResourceManager.GetString("ValidRequiredCitizenshipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter City.
        /// </summary>
        public static string ValidRequiredCity {
            get {
                return ResourceManager.GetString("ValidRequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Country.
        /// </summary>
        public static string ValidRequiredCountryId {
            get {
                return ResourceManager.GetString("ValidRequiredCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email.
        /// </summary>
        public static string ValidRequiredEmail {
            get {
                return ResourceManager.GetString("ValidRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter IC Number.
        /// </summary>
        public static string ValidRequiredICNo {
            get {
                return ResourceManager.GetString("ValidRequiredICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mobile Number.
        /// </summary>
        public static string ValidRequiredMobileNo {
            get {
                return ResourceManager.GetString("ValidRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Name.
        /// </summary>
        public static string ValidRequiredName {
            get {
                return ResourceManager.GetString("ValidRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Passport Number.
        /// </summary>
        public static string ValidRequiredPassportNo {
            get {
                return ResourceManager.GetString("ValidRequiredPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password.
        /// </summary>
        public static string ValidRequiredPassword {
            get {
                return ResourceManager.GetString("ValidRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Postcode.
        /// </summary>
        public static string ValidRequiredPostCode {
            get {
                return ResourceManager.GetString("ValidRequiredPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Retype Password.
        /// </summary>
        public static string ValidRequiredRetypePassword {
            get {
                return ResourceManager.GetString("ValidRequiredRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Role.
        /// </summary>
        public static string ValidRequiredRole {
            get {
                return ResourceManager.GetString("ValidRequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter State.
        /// </summary>
        public static string ValidRequiredStateId {
            get {
                return ResourceManager.GetString("ValidRequiredStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Email.
        /// </summary>
        public static string ValidTypeEmail {
            get {
                return ResourceManager.GetString("ValidTypeEmail", resourceCulture);
            }
        }
    }
}
