//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KMCCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KMCCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.KMCCategory", typeof(KMCCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add new category.
        /// </summary>
        public static string AlertFailCreate {
            get {
                return ResourceManager.GetString("AlertFailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete category.
        /// </summary>
        public static string AlertFailDelete {
            get {
                return ResourceManager.GetString("AlertFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update category.
        /// </summary>
        public static string AlertFailUpdate {
            get {
                return ResourceManager.GetString("AlertFailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category successfully added.
        /// </summary>
        public static string AlertSuccessCreate {
            get {
                return ResourceManager.GetString("AlertSuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category successfully deleted.
        /// </summary>
        public static string AlertSuccessDelete {
            get {
                return ResourceManager.GetString("AlertSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category successfully updated.
        /// </summary>
        public static string AlertSuccessUpdate {
            get {
                return ResourceManager.GetString("AlertSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category Title.
        /// </summary>
        public static string FieldTitle {
            get {
                return ResourceManager.GetString("FieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Category Title.
        /// </summary>
        public static string PlaceholderTitle {
            get {
                return ResourceManager.GetString("PlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string SidebarCategory {
            get {
                return ResourceManager.GetString("SidebarCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string SidebarCategoryList {
            get {
                return ResourceManager.GetString("SidebarCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TitleDescriptionList {
            get {
                return ResourceManager.GetString("TitleDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMC Category already registered in the system.
        /// </summary>
        public static string ValidExistName {
            get {
                return ResourceManager.GetString("ValidExistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Category Title.
        /// </summary>
        public static string ValidRequiredTitle {
            get {
                return ResourceManager.GetString("ValidRequiredTitle", resourceCulture);
            }
        }
    }
}
