//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewsArticle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsArticle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.NewsArticle", typeof(NewsArticle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadcrumbHome {
            get {
                return ResourceManager.GetString("BreadcrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Article.
        /// </summary>
        public static string BreadcrumbNewsArticle {
            get {
                return ResourceManager.GetString("BreadcrumbNewsArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Article Management.
        /// </summary>
        public static string BreadcrumbNewsArticleManagement {
            get {
                return ResourceManager.GetString("BreadcrumbNewsArticleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new publication by filling in publication details below..
        /// </summary>
        public static string CreateDescription {
            get {
                return ResourceManager.GetString("CreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create News &amp; Article.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Article Details.
        /// </summary>
        public static string HeadingDetails {
            get {
                return ResourceManager.GetString("HeadingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Article Settings.
        /// </summary>
        public static string HeadingSettings {
            get {
                return ResourceManager.GetString("HeadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information marked with.
        /// </summary>
        public static string MandatoryPrefix {
            get {
                return ResourceManager.GetString("MandatoryPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is mandatory..
        /// </summary>
        public static string MandatorySuffix {
            get {
                return ResourceManager.GetString("MandatorySuffix", resourceCulture);
            }
        }
    }
}
