//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to change email.
        /// </summary>
        public static string AlertFailChangeEmail {
            get {
                return ResourceManager.GetString("AlertFailChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to change password.
        /// </summary>
        public static string AlertFailChangePassword {
            get {
                return ResourceManager.GetString("AlertFailChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update profile.
        /// </summary>
        public static string AlertFailUpdateProfile {
            get {
                return ResourceManager.GetString("AlertFailUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully updated.
        /// </summary>
        public static string AlertSuccessChangeEmail {
            get {
                return ResourceManager.GetString("AlertSuccessChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated.
        /// </summary>
        public static string AlertSuccessChangePassword {
            get {
                return ResourceManager.GetString("AlertSuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile successfully updated.
        /// </summary>
        public static string AlertSuccessUpdateProfile {
            get {
                return ResourceManager.GetString("AlertSuccessUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FieldAddress {
            get {
                return ResourceManager.GetString("FieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Name.
        /// </summary>
        public static string FieldAgencyName {
            get {
                return ResourceManager.GetString("FieldAgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        public static string FieldCitizenship {
            get {
                return ResourceManager.GetString("FieldCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FieldCompanyAddress {
            get {
                return ResourceManager.GetString("FieldCompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string FieldCompanyName {
            get {
                return ResourceManager.GetString("FieldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string FieldCompanyPhoneNo {
            get {
                return ResourceManager.GetString("FieldCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No.
        /// </summary>
        public static string FieldCompanyRegNo {
            get {
                return ResourceManager.GetString("FieldCompanyRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FieldCompanyType {
            get {
                return ResourceManager.GetString("FieldCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string FieldConfirmPassword {
            get {
                return ResourceManager.GetString("FieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string FieldCountryId {
            get {
                return ResourceManager.GetString("FieldCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Email.
        /// </summary>
        public static string FieldCurrentEmail {
            get {
                return ResourceManager.GetString("FieldCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string FieldCurrentPassword {
            get {
                return ResourceManager.GetString("FieldCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC No.
        /// </summary>
        public static string FieldICNo {
            get {
                return ResourceManager.GetString("FieldICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the Terms of Use.
        /// </summary>
        public static string FieldIsTermAgreed {
            get {
                return ResourceManager.GetString("FieldIsTermAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FieldLoginId {
            get {
                return ResourceManager.GetString("FieldLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        public static string FieldMalaysian {
            get {
                return ResourceManager.GetString("FieldMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        public static string FieldMinistryId {
            get {
                return ResourceManager.GetString("FieldMinistryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string FieldMobileNo {
            get {
                return ResourceManager.GetString("FieldMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string FieldNewEmail {
            get {
                return ResourceManager.GetString("FieldNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string FieldNewPassword {
            get {
                return ResourceManager.GetString("FieldNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Malaysian.
        /// </summary>
        public static string FieldNonMalaysian {
            get {
                return ResourceManager.GetString("FieldNonMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string FieldPassportNo {
            get {
                return ResourceManager.GetString("FieldPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FieldPassword {
            get {
                return ResourceManager.GetString("FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string FieldPostCode {
            get {
                return ResourceManager.GetString("FieldPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please agree to Terms of Use.
        /// </summary>
        public static string FieldRequiredIsTermAgreed {
            get {
                return ResourceManager.GetString("FieldRequiredIsTermAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string FieldResetPasswordEmail {
            get {
                return ResourceManager.GetString("FieldResetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string FieldRetypePassword {
            get {
                return ResourceManager.GetString("FieldRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string FieldSector {
            get {
                return ResourceManager.GetString("FieldSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string FieldSectorId {
            get {
                return ResourceManager.GetString("FieldSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string FieldStateId {
            get {
                return ResourceManager.GetString("FieldStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 1.
        /// </summary>
        public static string PlaceholderAddress1 {
            get {
                return ResourceManager.GetString("PlaceholderAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 2.
        /// </summary>
        public static string PlaceholderAddress2 {
            get {
                return ResourceManager.GetString("PlaceholderAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Name.
        /// </summary>
        public static string PlaceholderAgencyName {
            get {
                return ResourceManager.GetString("PlaceholderAgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Citizenship.
        /// </summary>
        public static string PlaceholderCitizenship {
            get {
                return ResourceManager.GetString("PlaceholderCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PlaceholderCity {
            get {
                return ResourceManager.GetString("PlaceholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string PlaceholderCompanyName {
            get {
                return ResourceManager.GetString("PlaceholderCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string PlaceholderCompanyPhoneNo {
            get {
                return ResourceManager.GetString("PlaceholderCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Reg No.
        /// </summary>
        public static string PlaceholderCompRegNo {
            get {
                return ResourceManager.GetString("PlaceholderCompRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string PlaceholderCountryId {
            get {
                return ResourceManager.GetString("PlaceholderCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@gmail.com.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Number without -.
        /// </summary>
        public static string PlaceholderICNo {
            get {
                return ResourceManager.GetString("PlaceholderICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ministry.
        /// </summary>
        public static string PlaceholderMinistry {
            get {
                return ResourceManager.GetString("PlaceholderMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string PlaceholderMobileNo {
            get {
                return ResourceManager.GetString("PlaceholderMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string PlaceholderPassportNo {
            get {
                return ResourceManager.GetString("PlaceholderPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        public static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string PlaceholderPostCode {
            get {
                return ResourceManager.GetString("PlaceholderPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype your password.
        /// </summary>
        public static string PlaceholderRetypePassword {
            get {
                return ResourceManager.GetString("PlaceholderRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sector.
        /// </summary>
        public static string PlaceholderSectorId {
            get {
                return ResourceManager.GetString("PlaceholderSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string PlaceholderStateId {
            get {
                return ResourceManager.GetString("PlaceholderStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Agency Type.
        /// </summary>
        public static string PlaceholderType {
            get {
                return ResourceManager.GetString("PlaceholderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Malaysian Company.
        /// </summary>
        public static string TextForeign {
            get {
                return ResourceManager.GetString("TextForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Agency.
        /// </summary>
        public static string TextGovernment {
            get {
                return ResourceManager.GetString("TextGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Company.
        /// </summary>
        public static string TextLocal {
            get {
                return ResourceManager.GetString("TextLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TextSignIn {
            get {
                return ResourceManager.GetString("TextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string TitleResetPassword {
            get {
                return ResourceManager.GetString("TitleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email entered not matched with current email.
        /// </summary>
        public static string ValidCheckCurrentEmail {
            get {
                return ResourceManager.GetString("ValidCheckCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password entered not matched with current password.
        /// </summary>
        public static string ValidCheckCurrentPassword {
            get {
                return ResourceManager.GetString("ValidCheckCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Retype Password do not match.
        /// </summary>
        public static string ValidCompareRetypePassword {
            get {
                return ResourceManager.GetString("ValidCompareRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered in the system.
        /// </summary>
        public static string ValidIsExistEmail {
            get {
                return ResourceManager.GetString("ValidIsExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC No already registered in the system.
        /// </summary>
        public static string ValidIsExistICNo {
            get {
                return ResourceManager.GetString("ValidIsExistICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No already registered in the system.
        /// </summary>
        public static string ValidIsExistPassportNo {
            get {
                return ResourceManager.GetString("ValidIsExistPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered IC No digit length must be 12.
        /// </summary>
        public static string ValidLengthICNo {
            get {
                return ResourceManager.GetString("ValidLengthICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Contact No must be number.
        /// </summary>
        public static string ValidNumericCompanyPhoneNo {
            get {
                return ResourceManager.GetString("ValidNumericCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered IC No must be number.
        /// </summary>
        public static string ValidNumericICNo {
            get {
                return ResourceManager.GetString("ValidNumericICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Mobile No must be number.
        /// </summary>
        public static string ValidNumericMobileNo {
            get {
                return ResourceManager.GetString("ValidNumericMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Postcode must be number.
        /// </summary>
        public static string ValidNumericPostCode {
            get {
                return ResourceManager.GetString("ValidNumericPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Address.
        /// </summary>
        public static string ValidRequiredAddress {
            get {
                return ResourceManager.GetString("ValidRequiredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Agency Name.
        /// </summary>
        public static string ValidRequiredAgencyName {
            get {
                return ResourceManager.GetString("ValidRequiredAgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Citizenship.
        /// </summary>
        public static string ValidRequiredCitizenshipId {
            get {
                return ResourceManager.GetString("ValidRequiredCitizenshipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter City.
        /// </summary>
        public static string ValidRequiredCity {
            get {
                return ResourceManager.GetString("ValidRequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Name.
        /// </summary>
        public static string ValidRequiredCompanyName {
            get {
                return ResourceManager.GetString("ValidRequiredCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Contact No.
        /// </summary>
        public static string ValidRequiredCompanyPhoneNo {
            get {
                return ResourceManager.GetString("ValidRequiredCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Registration No.
        /// </summary>
        public static string ValidRequiredCompanyRegNo {
            get {
                return ResourceManager.GetString("ValidRequiredCompanyRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Country.
        /// </summary>
        public static string ValidRequiredCountryId {
            get {
                return ResourceManager.GetString("ValidRequiredCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Current Email.
        /// </summary>
        public static string ValidRequiredCurrentEmail {
            get {
                return ResourceManager.GetString("ValidRequiredCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Current Password.
        /// </summary>
        public static string ValidRequiredCurrentPassword {
            get {
                return ResourceManager.GetString("ValidRequiredCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email.
        /// </summary>
        public static string ValidRequiredEmail {
            get {
                return ResourceManager.GetString("ValidRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter IC No.
        /// </summary>
        public static string ValidRequiredICNo {
            get {
                return ResourceManager.GetString("ValidRequiredICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email.
        /// </summary>
        public static string ValidRequiredLoginId {
            get {
                return ResourceManager.GetString("ValidRequiredLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Ministry.
        /// </summary>
        public static string ValidRequiredMinistryId {
            get {
                return ResourceManager.GetString("ValidRequiredMinistryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mobile No.
        /// </summary>
        public static string ValidRequiredMobileNo {
            get {
                return ResourceManager.GetString("ValidRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Name.
        /// </summary>
        public static string ValidRequiredName {
            get {
                return ResourceManager.GetString("ValidRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter New Email.
        /// </summary>
        public static string ValidRequiredNewEmail {
            get {
                return ResourceManager.GetString("ValidRequiredNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter New Password.
        /// </summary>
        public static string ValidRequiredNewPassword {
            get {
                return ResourceManager.GetString("ValidRequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Passport No.
        /// </summary>
        public static string ValidRequiredPassportNo {
            get {
                return ResourceManager.GetString("ValidRequiredPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password.
        /// </summary>
        public static string ValidRequiredPassword {
            get {
                return ResourceManager.GetString("ValidRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Postcode.
        /// </summary>
        public static string ValidRequiredPostCode {
            get {
                return ResourceManager.GetString("ValidRequiredPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Retype Password.
        /// </summary>
        public static string ValidRequiredRetypePassword {
            get {
                return ResourceManager.GetString("ValidRequiredRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Sector.
        /// </summary>
        public static string ValidRequiredSectorId {
            get {
                return ResourceManager.GetString("ValidRequiredSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter State.
        /// </summary>
        public static string ValidRequiredStateId {
            get {
                return ResourceManager.GetString("ValidRequiredStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Email.
        /// </summary>
        public static string ValidTypeEmail {
            get {
                return ResourceManager.GetString("ValidTypeEmail", resourceCulture);
            }
        }
    }
}
