//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RnPEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RnPEnum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.RnPEnum", typeof(RnPEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string PubCategoryArticles {
            get {
                return ResourceManager.GetString("PubCategoryArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string PubCategoryBooks {
            get {
                return ResourceManager.GetString("PubCategoryBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts Sheet.
        /// </summary>
        public static string PubCategoryFactsSheet {
            get {
                return ResourceManager.GetString("PubCategoryFactsSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        public static string PubCategoryJournals {
            get {
                return ResourceManager.GetString("PubCategoryJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literature Reviews.
        /// </summary>
        public static string PubCategoryLiteratureReviews {
            get {
                return ResourceManager.GetString("PubCategoryLiteratureReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string PubCategoryReports {
            get {
                return ResourceManager.GetString("PubCategoryReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Papers.
        /// </summary>
        public static string PubCategoryResearchPapers {
            get {
                return ResourceManager.GetString("PubCategoryResearchPapers", resourceCulture);
            }
        }
    }
}
