//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RnPEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RnPEnum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.RnPEnum", typeof(RnPEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string PubCategoryArticles {
            get {
                return ResourceManager.GetString("PubCategoryArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string PubCategoryBooks {
            get {
                return ResourceManager.GetString("PubCategoryBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts Sheet.
        /// </summary>
        public static string PubCategoryFactsSheet {
            get {
                return ResourceManager.GetString("PubCategoryFactsSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        public static string PubCategoryJournals {
            get {
                return ResourceManager.GetString("PubCategoryJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literature Reviews.
        /// </summary>
        public static string PubCategoryLiteratureReviews {
            get {
                return ResourceManager.GetString("PubCategoryLiteratureReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string PubCategoryReports {
            get {
                return ResourceManager.GetString("PubCategoryReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Papers.
        /// </summary>
        public static string PubCategoryResearchPapers {
            get {
                return ResourceManager.GetString("PubCategoryResearchPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 1 (HoD).
        /// </summary>
        public static string SurveyApprovalLevelApprover1 {
            get {
                return ResourceManager.GetString("SurveyApprovalLevelApprover1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 2 (GM).
        /// </summary>
        public static string SurveyApprovalLevelApprover2 {
            get {
                return ResourceManager.GetString("SurveyApprovalLevelApprover2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 3 (CEO).
        /// </summary>
        public static string SurveyApprovalLevelApprover3 {
            get {
                return ResourceManager.GetString("SurveyApprovalLevelApprover3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier (Manager).
        /// </summary>
        public static string SurveyApprovalLevelVerifier {
            get {
                return ResourceManager.GetString("SurveyApprovalLevelVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string SurveyApprovalStatusApproved {
            get {
                return ResourceManager.GetString("SurveyApprovalStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Reviewed.
        /// </summary>
        public static string SurveyApprovalStatusNone {
            get {
                return ResourceManager.GetString("SurveyApprovalStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string SurveyApprovalStatusRejected {
            get {
                return ResourceManager.GetString("SurveyApprovalStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eLearning Survey.
        /// </summary>
        public static string SurveyCategoryeLearning {
            get {
                return ResourceManager.GetString("SurveyCategoryeLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Survey.
        /// </summary>
        public static string SurveyCategoryEvent {
            get {
                return ResourceManager.GetString("SurveyCategoryEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Survey.
        /// </summary>
        public static string SurveyCategoryResearch {
            get {
                return ResourceManager.GetString("SurveyCategoryResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Response.
        /// </summary>
        public static string SurveyResponseTypeActual {
            get {
                return ResourceManager.GetString("SurveyResponseTypeActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Response.
        /// </summary>
        public static string SurveyResponseTypeTesting {
            get {
                return ResourceManager.GetString("SurveyResponseTypeTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string SurveyStatusApproved {
            get {
                return ResourceManager.GetString("SurveyStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SurveyStatusNew {
            get {
                return ResourceManager.GetString("SurveyStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string SurveyStatusPublished {
            get {
                return ResourceManager.GetString("SurveyStatusPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted for Approval.
        /// </summary>
        public static string SurveyStatusSubmitted {
            get {
                return ResourceManager.GetString("SurveyStatusSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string SurveyStatusTrashed {
            get {
                return ResourceManager.GetString("SurveyStatusTrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished.
        /// </summary>
        public static string SurveyStatusUnpublished {
            get {
                return ResourceManager.GetString("SurveyStatusUnpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Survey.
        /// </summary>
        public static string SurveyTypePublic {
            get {
                return ResourceManager.GetString("SurveyTypePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Survey.
        /// </summary>
        public static string SurveyTypeTargeted {
            get {
                return ResourceManager.GetString("SurveyTypeTargeted", resourceCulture);
            }
        }
    }
}
