//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RnPForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RnPForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.RnPForm", typeof(RnPForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PubApprovalRemarks {
            get {
                return ResourceManager.GetString("PubApprovalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PubAuthor {
            get {
                return ResourceManager.GetString("PubAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Type.
        /// </summary>
        public static string PubCategoryID {
            get {
                return ResourceManager.GetString("PubCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Type.
        /// </summary>
        public static string PubCategoryName {
            get {
                return ResourceManager.GetString("PubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PubCategoryNameList {
            get {
                return ResourceManager.GetString("PubCategoryNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Author(s).
        /// </summary>
        public static string PubCoauthor {
            get {
                return ResourceManager.GetString("PubCoauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string PubDateAdded {
            get {
                return ResourceManager.GetString("PubDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PubDescription {
            get {
                return ResourceManager.GetString("PubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital copy.
        /// </summary>
        public static string PubDigitalcopy {
            get {
                return ResourceManager.GetString("PubDigitalcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Copy Price.
        /// </summary>
        public static string PubDPrice {
            get {
                return ResourceManager.GetString("PubDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Publication.
        /// </summary>
        public static string PubFree {
            get {
                return ResourceManager.GetString("PubFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard copy.
        /// </summary>
        public static string PubHardcopy {
            get {
                return ResourceManager.GetString("PubHardcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string PubHDcopy {
            get {
                return ResourceManager.GetString("PubHDcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Price.
        /// </summary>
        public static string PubHDPrice {
            get {
                return ResourceManager.GetString("PubHDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Copy Price.
        /// </summary>
        public static string PubHPrice {
            get {
                return ResourceManager.GetString("PubHPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN/ISSN/DOI.
        /// </summary>
        public static string PubISBN {
            get {
                return ResourceManager.GetString("PubISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PubLanguage {
            get {
                return ResourceManager.GetString("PubLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Of Approval.
        /// </summary>
        public static string PubProofOfApproval {
            get {
                return ResourceManager.GetString("PubProofOfApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Of Approval of Withdrawal.
        /// </summary>
        public static string PubProofOfWithdrawal {
            get {
                return ResourceManager.GetString("PubProofOfWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Purchased.
        /// </summary>
        public static string PubPurchaseCount {
            get {
                return ResourceManager.GetString("PubPurchaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string PubPurchaseDeliveryAddress {
            get {
                return ResourceManager.GetString("PubPurchaseDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PubStatus {
            get {
                return ResourceManager.GetString("PubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Balance.
        /// </summary>
        public static string PubStockBalance {
            get {
                return ResourceManager.GetString("PubStockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Title.
        /// </summary>
        public static string PubTitle {
            get {
                return ResourceManager.GetString("PubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string PubViewCount {
            get {
                return ResourceManager.GetString("PubViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Withdrawal.
        /// </summary>
        public static string PubWithdrawalReason {
            get {
                return ResourceManager.GetString("PubWithdrawalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PubWithdrawalRemarks {
            get {
                return ResourceManager.GetString("PubWithdrawalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Status.
        /// </summary>
        public static string PubWStatus {
            get {
                return ResourceManager.GetString("PubWStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Year.
        /// </summary>
        public static string PubYear {
            get {
                return ResourceManager.GetString("PubYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SurveyActive {
            get {
                return ResourceManager.GetString("SurveyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string SurveyApprovalApprovalDate {
            get {
                return ResourceManager.GetString("SurveyApprovalApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string SurveyApprovalRemarks {
            get {
                return ResourceManager.GetString("SurveyApprovalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Next Level Approval.
        /// </summary>
        public static string SurveyApprovalRequireNext {
            get {
                return ResourceManager.GetString("SurveyApprovalRequireNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        public static string SurveyApprovalStatus {
            get {
                return ResourceManager.GetString("SurveyApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string SurveyCategory {
            get {
                return ResourceManager.GetString("SurveyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Questions.
        /// </summary>
        public static string SurveyContents {
            get {
                return ResourceManager.GetString("SurveyContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Description.
        /// </summary>
        public static string SurveyDescription {
            get {
                return ResourceManager.GetString("SurveyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string SurveyEndDate {
            get {
                return ResourceManager.GetString("SurveyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string SurveyPictures {
            get {
                return ResourceManager.GetString("SurveyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Approval.
        /// </summary>
        public static string SurveyProofOfApproval {
            get {
                return ResourceManager.GetString("SurveyProofOfApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Answers.
        /// </summary>
        public static string SurveyResponseContents {
            get {
                return ResourceManager.GetString("SurveyResponseContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SurveyResponseResponseDate {
            get {
                return ResourceManager.GetString("SurveyResponseResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string SurveyStartDate {
            get {
                return ResourceManager.GetString("SurveyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SurveyStatus {
            get {
                return ResourceManager.GetString("SurveyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group.
        /// </summary>
        public static string SurveyTargetGroup {
            get {
                return ResourceManager.GetString("SurveyTargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string SurveyTemplate {
            get {
                return ResourceManager.GetString("SurveyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Title.
        /// </summary>
        public static string SurveyTitle {
            get {
                return ResourceManager.GetString("SurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Type.
        /// </summary>
        public static string SurveyType {
            get {
                return ResourceManager.GetString("SurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid date.
        /// </summary>
        public static string ValidInvalidSurveyEndDate {
            get {
                return ResourceManager.GetString("ValidInvalidSurveyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid date.
        /// </summary>
        public static string ValidInvalidSurveyStartDate {
            get {
                return ResourceManager.GetString("ValidInvalidSurveyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Author.
        /// </summary>
        public static string ValidRequiredAuthor {
            get {
                return ResourceManager.GetString("ValidRequiredAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Delivery Address.
        /// </summary>
        public static string ValidRequiredDeliveryAddress {
            get {
                return ResourceManager.GetString("ValidRequiredDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Description.
        /// </summary>
        public static string ValidRequiredDescription {
            get {
                return ResourceManager.GetString("ValidRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify ISBN/ISSN/DOI.
        /// </summary>
        public static string ValidRequiredISBN {
            get {
                return ResourceManager.GetString("ValidRequiredISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Language(s).
        /// </summary>
        public static string ValidRequiredLanguage {
            get {
                return ResourceManager.GetString("ValidRequiredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Remarks.
        /// </summary>
        public static string ValidRequiredRemarks {
            get {
                return ResourceManager.GetString("ValidRequiredRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify approval date.
        /// </summary>
        public static string ValidRequiredSurveyApprovalApprovalDate {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyApprovalApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Remarks.
        /// </summary>
        public static string ValidRequiredSurveyApprovalRemarks {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyApprovalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Status.
        /// </summary>
        public static string ValidRequiredSurveyApprovalStatus {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Module.
        /// </summary>
        public static string ValidRequiredSurveyCategory {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify some questions.
        /// </summary>
        public static string ValidRequiredSurveyContents {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Survey Description.
        /// </summary>
        public static string ValidRequiredSurveyDescription {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify End Date.
        /// </summary>
        public static string ValidRequiredSurveyEndDate {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Survey thumbnail.
        /// </summary>
        public static string ValidRequiredSurveyPictures {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Proof Of Approval.
        /// </summary>
        public static string ValidRequiredSurveyProofOfApproval {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyProofOfApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the Survey.
        /// </summary>
        public static string ValidRequiredSurveyResponseContents {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyResponseContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify response date.
        /// </summary>
        public static string ValidRequiredSurveyResponseResponseDate {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyResponseResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Start Date.
        /// </summary>
        public static string ValidRequiredSurveyStartDate {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate Target Group(s).
        /// </summary>
        public static string ValidRequiredSurveyTargetGroup {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyTargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Template name.
        /// </summary>
        public static string ValidRequiredSurveyTemplate {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Survey Title.
        /// </summary>
        public static string ValidRequiredSurveyTitle {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Survey Type.
        /// </summary>
        public static string ValidRequiredSurveyType {
            get {
                return ResourceManager.GetString("ValidRequiredSurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Publication Title.
        /// </summary>
        public static string ValidRequiredTitle {
            get {
                return ResourceManager.GetString("ValidRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Published Year.
        /// </summary>
        public static string ValidRequiredYear {
            get {
                return ResourceManager.GetString("ValidRequiredYear", resourceCulture);
            }
        }
    }
}
