//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RnPForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RnPForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.RnPForm", typeof(RnPForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PubAuthor {
            get {
                return ResourceManager.GetString("PubAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Type.
        /// </summary>
        public static string PubCategoryID {
            get {
                return ResourceManager.GetString("PubCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Type.
        /// </summary>
        public static string PubCategoryName {
            get {
                return ResourceManager.GetString("PubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PubCategoryNameList {
            get {
                return ResourceManager.GetString("PubCategoryNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Authors.
        /// </summary>
        public static string PubCoauthor {
            get {
                return ResourceManager.GetString("PubCoauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string PubDateAdded {
            get {
                return ResourceManager.GetString("PubDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PubDescription {
            get {
                return ResourceManager.GetString("PubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Copy Only.
        /// </summary>
        public static string PubDigitalcopy {
            get {
                return ResourceManager.GetString("PubDigitalcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Copy Price.
        /// </summary>
        public static string PubDPrice {
            get {
                return ResourceManager.GetString("PubDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Publication.
        /// </summary>
        public static string PubFree {
            get {
                return ResourceManager.GetString("PubFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Copy Only.
        /// </summary>
        public static string PubHardcopy {
            get {
                return ResourceManager.GetString("PubHardcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Copy and Digital.
        /// </summary>
        public static string PubHDcopy {
            get {
                return ResourceManager.GetString("PubHDcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Price.
        /// </summary>
        public static string PubHDPrice {
            get {
                return ResourceManager.GetString("PubHDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Copy Price.
        /// </summary>
        public static string PubHPrice {
            get {
                return ResourceManager.GetString("PubHPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string PubISBN {
            get {
                return ResourceManager.GetString("PubISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PubLanguage {
            get {
                return ResourceManager.GetString("PubLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Of Approval.
        /// </summary>
        public static string PubProofOfApproval {
            get {
                return ResourceManager.GetString("PubProofOfApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Of Approval of Withdrawal.
        /// </summary>
        public static string PubProofOfWithdrawal {
            get {
                return ResourceManager.GetString("PubProofOfWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Purchased.
        /// </summary>
        public static string PubPurchaseCount {
            get {
                return ResourceManager.GetString("PubPurchaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PubStatus {
            get {
                return ResourceManager.GetString("PubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Balance.
        /// </summary>
        public static string PubStockBalance {
            get {
                return ResourceManager.GetString("PubStockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PubTitle {
            get {
                return ResourceManager.GetString("PubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string PubViewCount {
            get {
                return ResourceManager.GetString("PubViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Withdrawal.
        /// </summary>
        public static string PubWithdrawalReason {
            get {
                return ResourceManager.GetString("PubWithdrawalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Status.
        /// </summary>
        public static string PubWStatus {
            get {
                return ResourceManager.GetString("PubWStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string PubYear {
            get {
                return ResourceManager.GetString("PubYear", resourceCulture);
            }
        }
    }
}
