//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Survey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Survey() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Survey", typeof(Survey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadcrumbHome {
            get {
                return ResourceManager.GetString("BreadcrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Surveys.
        /// </summary>
        public static string BreadcrumbPublishedSurveys {
            get {
                return ResourceManager.GetString("BreadcrumbPublishedSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research &amp; Publication.
        /// </summary>
        public static string BreadcrumbRnP {
            get {
                return ResourceManager.GetString("BreadcrumbRnP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Results.
        /// </summary>
        public static string BreadcrumbSurveyResults {
            get {
                return ResourceManager.GetString("BreadcrumbSurveyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string BreadcrumbSurveys {
            get {
                return ResourceManager.GetString("BreadcrumbSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey.
        /// </summary>
        public static string ButtonCreateSurvey {
            get {
                return ResourceManager.GetString("ButtonCreateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review for Submission.
        /// </summary>
        public static string ButtonReviewForSubmission {
            get {
                return ResourceManager.GetString("ButtonReviewForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Draft.
        /// </summary>
        public static string ButtonSaveAsDraft {
            get {
                return ResourceManager.GetString("ButtonSaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new survey by filling in survey details below..
        /// </summary>
        public static string CreateDescription {
            get {
                return ResourceManager.GetString("CreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing survey that was saved as draft..
        /// </summary>
        public static string EditDescription {
            get {
                return ResourceManager.GetString("EditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Survey.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Details.
        /// </summary>
        public static string HeadingDetails {
            get {
                return ResourceManager.GetString("HeadingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Settings.
        /// </summary>
        public static string HeadingSettings {
            get {
                return ResourceManager.GetString("HeadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit, delete and manage surveys..
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Surveys.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string LabelDuration {
            get {
                return ResourceManager.GetString("LabelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string LabelFilters {
            get {
                return ResourceManager.GetString("LabelFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string LabelResponse {
            get {
                return ResourceManager.GetString("LabelResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string LabelStats {
            get {
                return ResourceManager.GetString("LabelStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string LabelSummary {
            get {
                return ResourceManager.GetString("LabelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabular Output.
        /// </summary>
        public static string LabelTabularOutput {
            get {
                return ResourceManager.GetString("LabelTabularOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View survey results and statistics..
        /// </summary>
        public static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Published Surveys.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information marked with.
        /// </summary>
        public static string MandatoryPrefix {
            get {
                return ResourceManager.GetString("MandatoryPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is mandatory..
        /// </summary>
        public static string MandatorySuffix {
            get {
                return ResourceManager.GetString("MandatorySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ResultsDescription {
            get {
                return ResourceManager.GetString("ResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        public static string ResultsRefNo {
            get {
                return ResourceManager.GetString("ResultsRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for Survey.
        /// </summary>
        public static string ResultsTitle {
            get {
                return ResourceManager.GetString("ResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify system settings for Survey.
        /// </summary>
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Survey Details.
        /// </summary>
        public static string StageEditDetails {
            get {
                return ResourceManager.GetString("StageEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill In Survey Details.
        /// </summary>
        public static string StageEnterDetails {
            get {
                return ResourceManager.GetString("StageEnterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Submission.
        /// </summary>
        public static string StageReview {
            get {
                return ResourceManager.GetString("StageReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Survey Category.
        /// </summary>
        public static string StageSelectCategory {
            get {
                return ResourceManager.GetString("StageSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Results.
        /// </summary>
        public static string TabRawResults {
            get {
                return ResourceManager.GetString("TabRawResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string TabStatistics {
            get {
                return ResourceManager.GetString("TabStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string TabSummary {
            get {
                return ResourceManager.GetString("TabSummary", resourceCulture);
            }
        }
    }
}
