//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TOT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TOT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.TOT", typeof(TOT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to add report.
        /// </summary>
        public static string AlertCreateFail {
            get {
                return ResourceManager.GetString("AlertCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report successfully added.
        /// </summary>
        public static string AlertCreateSuccess {
            get {
                return ResourceManager.GetString("AlertCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete report.
        /// </summary>
        public static string AlertDeleteFail {
            get {
                return ResourceManager.GetString("AlertDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report successfully deleted.
        /// </summary>
        public static string AlertDeleteSuccess {
            get {
                return ResourceManager.GetString("AlertDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update report.
        /// </summary>
        public static string AlertEditFail {
            get {
                return ResourceManager.GetString("AlertEditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report successfully updated.
        /// </summary>
        public static string AlertEditSuccess {
            get {
                return ResourceManager.GetString("AlertEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Range.
        /// </summary>
        public static string FieldAgeRange {
            get {
                return ResourceManager.GetString("FieldAgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string FieldAttachment {
            get {
                return ResourceManager.GetString("FieldAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string FieldCourse {
            get {
                return ResourceManager.GetString("FieldCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FieldDate {
            get {
                return ResourceManager.GetString("FieldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string FieldEndDate {
            get {
                return ResourceManager.GetString("FieldEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string FieldEndTime {
            get {
                return ResourceManager.GetString("FieldEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string FieldModule {
            get {
                return ResourceManager.GetString("FieldModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Female Participant.
        /// </summary>
        public static string FieldNoOfFemale {
            get {
                return ResourceManager.GetString("FieldNoOfFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Male Participant.
        /// </summary>
        public static string FieldNoOfMale {
            get {
                return ResourceManager.GetString("FieldNoOfMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Participant.
        /// </summary>
        public static string FieldNoOfParticipant {
            get {
                return ResourceManager.GetString("FieldNoOfParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Range.
        /// </summary>
        public static string FieldSalaryRange {
            get {
                return ResourceManager.GetString("FieldSalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string FieldStartDate {
            get {
                return ResourceManager.GetString("FieldStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string FieldStartTime {
            get {
                return ResourceManager.GetString("FieldStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string FieldVenue {
            get {
                return ResourceManager.GetString("FieldVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Age Range.
        /// </summary>
        public static string PlaceholderAgeRange {
            get {
                return ResourceManager.GetString("PlaceholderAgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course.
        /// </summary>
        public static string PlaceholderCourse {
            get {
                return ResourceManager.GetString("PlaceholderCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter End Date.
        /// </summary>
        public static string PlaceholderEndDate {
            get {
                return ResourceManager.GetString("PlaceholderEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Module.
        /// </summary>
        public static string PlaceholderModule {
            get {
                return ResourceManager.GetString("PlaceholderModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Salary Range.
        /// </summary>
        public static string PlaceholderSalaryRange {
            get {
                return ResourceManager.GetString("PlaceholderSalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Start Date.
        /// </summary>
        public static string PlaceholderStartDate {
            get {
                return ResourceManager.GetString("PlaceholderStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Venue.
        /// </summary>
        public static string PlaceholderVenue {
            get {
                return ResourceManager.GetString("PlaceholderVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of report from trainer.
        /// </summary>
        public static string TitleDescriptionList {
            get {
                return ResourceManager.GetString("TitleDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Of Trainer Report.
        /// </summary>
        public static string TitleList {
            get {
                return ResourceManager.GetString("TitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Age Range.
        /// </summary>
        public static string ValidRequiredAgeRange {
            get {
                return ResourceManager.GetString("ValidRequiredAgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Course.
        /// </summary>
        public static string ValidRequiredCourse {
            get {
                return ResourceManager.GetString("ValidRequiredCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter End Date.
        /// </summary>
        public static string ValidRequiredEndDate {
            get {
                return ResourceManager.GetString("ValidRequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter End Time.
        /// </summary>
        public static string ValidRequiredEndTime {
            get {
                return ResourceManager.GetString("ValidRequiredEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Module.
        /// </summary>
        public static string ValidRequiredModule {
            get {
                return ResourceManager.GetString("ValidRequiredModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter No of Female Participant.
        /// </summary>
        public static string ValidRequiredNoOfFemale {
            get {
                return ResourceManager.GetString("ValidRequiredNoOfFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter No of Male Participant.
        /// </summary>
        public static string ValidRequiredNoOfMale {
            get {
                return ResourceManager.GetString("ValidRequiredNoOfMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Salary Range.
        /// </summary>
        public static string ValidRequiredSalaryRange {
            get {
                return ResourceManager.GetString("ValidRequiredSalaryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Start Date.
        /// </summary>
        public static string ValidRequiredStartDate {
            get {
                return ResourceManager.GetString("ValidRequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Start Time.
        /// </summary>
        public static string ValidRequiredStartTime {
            get {
                return ResourceManager.GetString("ValidRequiredStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Venue.
        /// </summary>
        public static string ValidRequiredVenue {
            get {
                return ResourceManager.GetString("ValidRequiredVenue", resourceCulture);
            }
        }
    }
}
