//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string FieldAddress {
            get {
                return ResourceManager.GetString("FieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string FieldCompanyName {
            get {
                return ResourceManager.GetString("FieldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phne No.
        /// </summary>
        public static string FieldCompanyPhoneNo {
            get {
                return ResourceManager.GetString("FieldCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Regstration No.
        /// </summary>
        public static string FieldCompanyRegNo {
            get {
                return ResourceManager.GetString("FieldCompanyRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string FieldConfirmPassword {
            get {
                return ResourceManager.GetString("FieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC No.
        /// </summary>
        public static string FieldICNo {
            get {
                return ResourceManager.GetString("FieldICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string FieldMobileNo {
            get {
                return ResourceManager.GetString("FieldMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string FieldPostCode {
            get {
                return ResourceManager.GetString("FieldPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string FieldSector {
            get {
                return ResourceManager.GetString("FieldSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string FieldSectorId {
            get {
                return ResourceManager.GetString("FieldSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string FieldStateId {
            get {
                return ResourceManager.GetString("FieldStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 1.
        /// </summary>
        public static string PlaceholderAddress1 {
            get {
                return ResourceManager.GetString("PlaceholderAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address line 2.
        /// </summary>
        public static string PlaceholderAddress2 {
            get {
                return ResourceManager.GetString("PlaceholderAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PlaceholderCity {
            get {
                return ResourceManager.GetString("PlaceholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string PlaceholderCompanyName {
            get {
                return ResourceManager.GetString("PlaceholderCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone No.
        /// </summary>
        public static string PlaceholderCompanyPhoneNo {
            get {
                return ResourceManager.GetString("PlaceholderCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registration No.
        /// </summary>
        public static string PlaceholderCompRegNo {
            get {
                return ResourceManager.GetString("PlaceholderCompRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC No.
        /// </summary>
        public static string PlaceholderICNo {
            get {
                return ResourceManager.GetString("PlaceholderICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string PlaceholderMobileNo {
            get {
                return ResourceManager.GetString("PlaceholderMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string PlaceholderPostCode {
            get {
                return ResourceManager.GetString("PlaceholderPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sector.
        /// </summary>
        public static string PlaceholderSectorId {
            get {
                return ResourceManager.GetString("PlaceholderSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string PlaceholderStateId {
            get {
                return ResourceManager.GetString("PlaceholderStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Address.
        /// </summary>
        public static string ValidRequiredAddress {
            get {
                return ResourceManager.GetString("ValidRequiredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter City.
        /// </summary>
        public static string ValidRequiredCity {
            get {
                return ResourceManager.GetString("ValidRequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Name.
        /// </summary>
        public static string ValidRequiredCompanyName {
            get {
                return ResourceManager.GetString("ValidRequiredCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Phone No.
        /// </summary>
        public static string ValidRequiredCompanyPhoneNo {
            get {
                return ResourceManager.GetString("ValidRequiredCompanyPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email.
        /// </summary>
        public static string ValidRequiredEmail {
            get {
                return ResourceManager.GetString("ValidRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter IC No.
        /// </summary>
        public static string ValidRequiredICNo {
            get {
                return ResourceManager.GetString("ValidRequiredICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mobile No.
        /// </summary>
        public static string ValidRequiredMobileNo {
            get {
                return ResourceManager.GetString("ValidRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Name.
        /// </summary>
        public static string ValidRequiredName {
            get {
                return ResourceManager.GetString("ValidRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password.
        /// </summary>
        public static string ValidRequiredPassword {
            get {
                return ResourceManager.GetString("ValidRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Postcode.
        /// </summary>
        public static string ValidRequiredPostCode {
            get {
                return ResourceManager.GetString("ValidRequiredPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Retype Password.
        /// </summary>
        public static string ValidRequiredRetypePassword {
            get {
                return ResourceManager.GetString("ValidRequiredRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Sector.
        /// </summary>
        public static string ValidRequiredSectorId {
            get {
                return ResourceManager.GetString("ValidRequiredSectorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select State.
        /// </summary>
        public static string ValidRequiredStateId {
            get {
                return ResourceManager.GetString("ValidRequiredStateId", resourceCulture);
            }
        }
    }
}
